package top.qianxinyao.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewslogs<M extends BaseNewslogs<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setNewsId(java.lang.Long newsId) {
		set("news_id", newsId);
	}

	public java.lang.Long getNewsId() {
		return get("news_id");
	}

	public void setViewTime(java.util.Date viewTime) {
		set("view_time", viewTime);
	}

	public java.util.Date getViewTime() {
		return get("view_time");
	}

	public void setPreferDegree(java.lang.Integer preferDegree) {
		set("prefer_degree", preferDegree);
	}

	public java.lang.Integer getPreferDegree() {
		return get("prefer_degree");
	}

}
